image: node:20-alpine

stages:
  - test

run_postman_tests:
  stage: test
  script:
    - echo "Startar automatiserade API-tester med Newman..."
    - npx newman run VideoGameAPI.postman_collection.json -e Local.postman_environment.json
  artifacts:
    when: always
    paths:
      - test-results.json
    expire_in: 30 days
  only:
    - main
    - develop
    - merge_requests
    